# Generated by Django 2.0.3 on 2018-03-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_dateexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
