# Generated by Django 2.0.3 on 2018-03-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20180313_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateTimeField()),
            ],
        ),
    ]
