# Generated by Django 2.0.3 on 2018-03-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simple',
            name='url',
            field=models.URLField(default='www.example.com'),
        ),
    ]
